const actionMaker = require('./lib/actionMaker');

const val = [
    {
        "calendar":
            [
                {
                    "kind":
                        "calendar#event",
                    "etag":
                        "\"3244831055786000\"",
                    "id":
                        "2n8nivv1ks77cucns0b7rejer0",
                    "status":
                        "confirmed",
                    "htmlLink":
                        "https://www.google.com/calendar/event?eid=Mm44bml2djFrczc3Y3VjbnMwYjdyZWplcjAgdThwbmhqaGMwMHMzMzI1ZjBvZ2wxcTRnc29AZw",
                    "created":
                        "2021-05-30T18:08:03.000Z",
                    "updated":
                        "2021-05-30T22:58:47.893Z",
                    "summary":
                        "create page range2",
                    "creator":
                    {
                        "email":
                            "pdpxpd@gmail.com"
                    },
                    "organizer":
                    {
                        "email":
                            "u8pnhjhc00s3325f0ogl1q4gso@group.calendar.google.com",
                        "displayName":
                            "test notion",
                        "self":
                            true
                    },
                    "start":
                    {
                        "dateTime":
                            "2021-05-29T10:15:00+09:00"
                    },
                    "end":
                    {
                        "dateTime":
                            "2021-05-30T10:45:00+09:00"
                    },
                    "iCalUID":
                        "2n8nivv1ks77cucns0b7rejer0@google.com",
                    "sequence":
                        0,
                    "reminders":
                    {
                        "useDefault":
                            true
                    },
                    "eventType":
                        "default"
                },
                {
                    "kind":
                        "calendar#event",
                    "etag":
                        "\"3244833965478000\"",
                    "id":
                        "7l48nhctsojbae04tglqi9hlun",
                    "status":
                        "confirmed",
                    "htmlLink":
                        "https://www.google.com/calendar/event?eid=N2w0OG5oY3Rzb2piYWUwNHRnbHFpOWhsdW4gdThwbmhqaGMwMHMzMzI1ZjBvZ2wxcTRnc29AZw",
                    "created":
                        "2021-05-30T18:07:54.000Z",
                    "updated":
                        "2021-05-30T23:23:02.739Z",
                    "summary":
                        "create page range",
                    "creator":
                    {
                        "email":
                            "pdpxpd@gmail.com"
                    },
                    "organizer":
                    {
                        "email":
                            "u8pnhjhc00s3325f0ogl1q4gso@group.calendar.google.com",
                        "displayName":
                            "test notion",
                        "self":
                            true
                    },
                    "start":
                    {
                        "dateTime":
                            "2021-05-29T10:15:00+09:00"
                    },
                    "end":
                    {
                        "dateTime":
                            "2021-05-29T10:45:00+09:00"
                    },
                    "iCalUID":
                        "7l48nhctsojbae04tglqi9hlun@google.com",
                    "sequence":
                        0,
                    "reminders":
                    {
                        "useDefault":
                            true
                    },
                    "eventType":
                        "default"
                },
                {
                    "kind":
                        "calendar#event",
                    "etag":
                        "\"3244821397594000\"",
                    "id":
                        "6rj9lkj6m5q9sgh647e9dcfe3f",
                    "status":
                        "confirmed",
                    "htmlLink":
                        "https://www.google.com/calendar/event?eid=NnJqOWxrajZtNXE5c2doNjQ3ZTlkY2ZlM2YgdThwbmhqaGMwMHMzMzI1ZjBvZ2wxcTRnc29AZw",
                    "created":
                        "2021-05-30T18:06:52.000Z",
                    "updated":
                        "2021-05-31T01:09:35.916Z",
                    "summary":
                        "create page",
                    "description":
                        "NOTION_ID: f1235976-7590-4e49-afaf-79810760d5de\nhttps://notion.so/f123597675904e49afaf79810760d5de ",
                    "creator":
                    {
                        "email":
                            "pdpxpd@gmail.com"
                    },
                    "organizer":
                    {
                        "email":
                            "u8pnhjhc00s3325f0ogl1q4gso@group.calendar.google.com",
                        "displayName":
                            "test notion",
                        "self":
                            true
                    },
                    "start":
                    {
                        "date":
                            "2021-05-29"
                    },
                    "end":
                    {
                        "date":
                            "2021-05-30"
                    },
                    "transparency":
                        "transparent",
                    "iCalUID":
                        "6rj9lkj6m5q9sgh647e9dcfe3f@google.com",
                    "sequence":
                        0,
                    "reminders":
                    {
                        "useDefault":
                            false
                    },
                    "eventType":
                        "default"
                }
            ]
    },
    {
        "notion":
            [
                {
                    "object":
                        "page",
                    "id":
                        "f1235976-7590-4e49-afaf-79810760d5de",
                    "created_time":
                        "2021-05-31T01:09:34.876Z",
                    "last_edited_time":
                        "2021-05-31T01:09:34.876Z",
                    "parent":
                    {
                        "type":
                            "database_id",
                        "database_id":
                            "2ad4848e-ab72-4165-8086-0d1d2efc34c6"
                    },
                    "archived":
                        false,
                    "properties":
                    {
                        "FIX-End":
                        {
                            "id":
                                "<vVo",
                            "type":
                                "date",
                            "date":
                            {
                                "start":
                                    "2021-05-29T00:00:00.000+00:00",
                                "end":
                                    null
                            }
                        },
                        "GCal Id":
                        {
                            "id":
                                "Czo|",
                            "type":
                                "rich_text",
                            "rich_text":
                                [
                                    {
                                        "type":
                                            "text",
                                        "text":
                                        {
                                            "content":
                                                "6rj9lkj6m5q9sgh647e9dcfe3f",
                                            "link":
                                                null
                                        },
                                        "annotations":
                                        {
                                            "bold":
                                                false,
                                            "italic":
                                                false,
                                            "strikethrough":
                                                false,
                                            "underline":
                                                false,
                                            "code":
                                                false,
                                            "color":
                                                "default"
                                        },
                                        "plain_text":
                                            "6rj9lkj6m5q9sgh647e9dcfe3f",
                                        "href":
                                            null
                                    }
                                ]
                        },
                        "Last Edited Time":
                        {
                            "id":
                                "yGwT",
                            "type":
                                "last_edited_time",
                            "last_edited_time":
                                "2021-05-31T01:09:34.876Z"
                        },
                        "Name":
                        {
                            "id":
                                "title",
                            "type":
                                "title",
                            "title":
                                [
                                    {
                                        "type":
                                            "text",
                                        "text":
                                        {
                                            "content":
                                                "create page",
                                            "link":
                                                null
                                        },
                                        "annotations":
                                        {
                                            "bold":
                                                false,
                                            "italic":
                                                false,
                                            "strikethrough":
                                                false,
                                            "underline":
                                                false,
                                            "code":
                                                false,
                                            "color":
                                                "default"
                                        },
                                        "plain_text":
                                            "create page",
                                        "href":
                                            null
                                    }
                                ]
                        }
                    }
                }
            ]
    }
];
const result = actionMaker.main(val.map(v => ({json: v})));

console.log(JSON.stringify(result, null, 2));